name: Check
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  nuxt:
    name: Nuxt Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm run build

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm exec prettier --check .

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup
      - run: pnpm exec eslint .

  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup
      - if: github.event_name == 'push'
        run: pnpm exec commitlint -- --last --verbose
      - if: github.event_name == 'pull_request'
        run: pnpm exec commitlint -- --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
